#创建系列api，每天调用一次
name: Run Api.Write

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: '12 23 * * *'
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install requests and xlsxwriter #安装模块
      run: |
        pip install requests
        pip install xlsxwriter
    - name: run api.Write #api调用
      env: 
        EMAIL: ${{ secrets.EMAIL }} 
        GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        GH_REPO: ${{ github.repository }}
        CONFIG: ${{ secrets.CONFIG }} 
        REDIRECT_URI: ${{ secrets.REDIRECT_URL }}   
      run: |
        python ApiOfWrite.py
